### ISSUE TITLE
Using sqlite3 with react and typescript

### ISSUE THREAD

**Issue by Juancard** [karolis-sh/electron-snowpack#63]
Hi, I've been trying to make sqlite3 work on the react-typescript example ([(link)](https://github.com/karolis-sh/electron-snowpack/tree/main/examples/react-typescript)) and it doesn't seem to work, have any of you tried anything similar?

The steps to reproduce are as follows. 

1) First, add a postinstall step in `package.json`:
```json
"scripts": {
   "postinstall": "install-app-deps"
   ...
}
```

2) Install sqlite3 and builder
```bash
npm install --save-dev electron-builder
npm install --save sqlite3
npm run postinstall
```

3) Add these lines to `src/main/index.ts`
```js
import sqlite3 from "sqlite3";
console.log(sqlite3); 
```
4) `npm run dev`

And then it throws the error:
```bash
[electron] A JavaScript error occurred in the main process
Uncaught Exception:
Error: package.json does not exist at /opt/electron-snowpack/examples/react-typescript/dist/package.json
    at Object.exports2.find (/opt/electron-snowpack/examples/react-typescript/dist/main/index.js:10559:15)
    at node_modules/sqlite3/lib/sqlite3-binding.js (/opt/electron-snowpack/examples/react-typescript/dist/main/index.js:10778:31)
    at __require (/opt/electron-snowpack/examples/react-typescript/dist/main/index.js:9:44)
    at node_modules/sqlite3/lib/sqlite3.js (/opt/electron-snowpack/examples/react-typescript/dist/main/index.js:10828:20)
    at __require (/opt/electron-snowpack/examples/react-typescript/dist/main/index.js:9:44)
    at Object.<anonymous> (/opt/electron-snowpack/examples/react-typescript/dist/main/index.js:11000:33)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
```

**Comment by karolis-sh** [comment]
Hey, if this is still of interest to you, could you provide a bare-bones reproduction repository?
